<a href="https://colab.research.google.com/github/VikaSvyat/DI_Bootcamp/blob/main/colab/IntrotoNumpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#Create a 1D NumPy array containing numbers from 0 to 9.
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
arr = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
arr

array([3, 2, 0, 1, 2])

In [8]:
#Create a 3x3 NumPy array with values ranging from 1 to 9.
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#Create a 2D NumPy array of shape (4, 5) filled with random numbers.
arr = np.random.random([4,5]).round(2)
arr

array([[0.3 , 0.76, 0.52, 0.03, 0.16],
       [0.01, 0.04, 0.67, 0.17, 0.52],
       [0.01, 0.01, 0.38, 0.74, 0.18],
       [0.5 , 0.85, 0.82, 0.2 , 0.17]])

In [18]:
#Select the second row from a given 2D NumPy array.
print(arr.ndim)
print(arr.shape)
print(arr[1])

2
(4, 5)
[0.01 0.04 0.67 0.17 0.52]


In [24]:
#Reverse the order of elements in a given 1D NumPy array (first element becomes last).
row  = np.arange(0,10)
print(row[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [23]:
#Create a 4x4 identity matrix using NumPy.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Find the sum and average of a given 1D array.
print(f"Average: {row.mean()}")
print(f"Sum: {row.sum()}")

Average: 4.5
Sum: 45


In [30]:
#Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
#Extract all odd numbers from a given NumPy array.
row[row%2==1]

array([1, 3, 5, 7, 9])